// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqegFtuY20RaiV4W_YKngnq7VkFlb9AiQ',
    appId: '1:686437319963:web:ea8dbfa63f4895fcf13fbe',
    messagingSenderId: '686437319963',
    projectId: 'rb-atharv',
    authDomain: 'rb-atharv.firebaseapp.com',
    storageBucket: 'rb-atharv.appspot.com',
    measurementId: 'G-D46TH3MR9P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_c0TWHoQ3fMhLINZacbIsAkU72qf6zGw',
    appId: '1:686437319963:android:ac4714e8b911149af13fbe',
    messagingSenderId: '686437319963',
    projectId: 'rb-atharv',
    storageBucket: 'rb-atharv.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkcGnd5vj3MLIxKYhUZzeoGEK6ZZOJCFE',
    appId: '1:686437319963:ios:8749275f6cdcf923f13fbe',
    messagingSenderId: '686437319963',
    projectId: 'rb-atharv',
    storageBucket: 'rb-atharv.appspot.com',
    androidClientId: '686437319963-r5hjelnfj4kt60mkb1sl6kgio6c75dq2.apps.googleusercontent.com',
    iosClientId: '686437319963-ff9obo0vb3fgjmtq9qnaa578db56e6un.apps.googleusercontent.com',
    iosBundleId: 'com.example.rba',
  );
}
